### ISSUE TITLE
tv_grab_nl3.conf

### ISSUE THREAD

**Issue by filoor** [tvgrabbers/tvgrabpyAPI#13]
The file is not there 

pi@raspberrypi:/home/tvgrabpyAPI-master $ sudo python ./tv_grab_nl3.py --configure
Loaded the English texts file
Using config file: /etc/tvgrabpyAPI/tv_grab_nl3_py.conf
File: "/etc/tvgrabpyAPI/tv_grab_nl3_py.conf" not found or could not be accessed.
  Downloading tv_grab_API.json...
  Downloading tv_grab_nl.json...
The channel/source matching data is newer!
Nickelodeon and Spike changes, use the following:
         0-89: Nickelodeon 24/7.
        0-467: Spike 24/7.
1-nickelodeon: Combined Nickelodeon/Spike.
PRIME is now Play More.
HBO and Fox Life have closed.
Omroep Brabant is now 24/7 on Canal Digitaal, use 0-114.
Wild FM changed name to Wild Hitradio.
Creating config file: /etc/tvgrabpyAPI/tv_grab_nl3_py.conf
Verifying the database
Error reading the base-channels-page: http://www.primo.eu/Tv%20programma's%20in%20volledig%20scherm%20bekijken
Error reading the base-channels-page: http://www.primo.eu/Tv%20programma's%20in%20volledig%20scherm%20bekijken
Unable to get channel info from primo.eu
Not all channel info could be retrieved.
Try again in 15 minutes or so; or disable the failing source.
Waiting for all remaining threads to finish

**Comment by hikavdh** [comment]
> Using config file: /etc/tvgrabpyAPI/tv_grab_nl3_py.conf
This is because you are running as root (sudo python ./tv_grab_nl3.py --configure)
Which is ok for configure, but is disallowed for the actual fetch. The configuration will now be stored in a common place to be used by any user whenever he/she does not have it's own configuration in ~/.xmltv. The database however will not be shared and will be stored in  ~/.xmltv for every separate user. Unless of cause you specify a different location. If you want the configuration to be user specific don't use `sudo`

> File: "/etc/tvgrabpyAPI/tv_grab_nl3_py.conf" not found or could not be accessed.
This is because it obviously is your first time, so it could not jet exist! ;-)

I just now checked the channels url for primo and it seems some things have changed there I'll checkk further and will update the source-file. If you for now add --disable-source 9 your configure will succeed but without the primo.eu source. You can once I have fixed this run configure again without --disable-source 9 and the data will get added to your configuration.

**Comment by hikavdh** [comment]
Ok, I found it and fixed it. Primo.eu had added a weird tag somewhere: `<!--Nitin's code : drop down for responsiveness --!>` which broke the parsing. It now gets removed before starting parsing. If you try again in a few minutes, the new source-file will get downloaded.
