### ISSUE TITLE
Dont get output for canvas the last couple of days

### ISSUE THREAD

**Issue by pensionado** [tvgrabbers/tvgrabpyAPI#25]
It appears than since a few days (suspect 3) I don't get output for canvas, I see plenty of entries in the logs for programs from canvas, but no output in the xml output. Cant find any other error messages either, they appear to sink in a black hole. See logs and xml output attached.
[tvgrab.zip](https://github.com/tvgrabbers/tvgrabpyAPI/files/1477451/tvgrab.zip)

**Comment by kyl416** [comment]
It looks like you're also not fetching any data from humo.be or npo.nl in your log.

Can you run --clear_cache and --configure and then try again?

**Comment by hikavdh** [comment]
I see the same in my output. It merges alright and then just before adding it to the XML file it disappears. I have to look further for any cause. So far all other channels seem unaffected.

**Comment by hikavdh** [comment]
The night from Tuesday to Wednesday it was still included. But after then I do no longer see start times rounded to the minute. So that is older data.
I at this moment can not find a way for this to happen without some fatal error, which is not there????

**Comment by hikavdh** [comment]
I've been trying to reproduce the normal faulty output from earlier this evening and I can't. I'll check tomorrow the regular output.  Let me know what you see on your next output.

**Comment by pensionado** [comment]
Output this morning looks normal, canvas is back. Mystery ;-)

**Comment by hikavdh** [comment]
Did you run --configure? Because if you, like me, did, my guess is that the channelid updates Kyle did around the time the problem started on some Flemish channels caused it. A --configure also does some updates on the database that some of the sources need and again my guess is that in some mysterious way that caused it again to work properly. The weirdest is then that there was no error.

**Comment by pensionado** [comment]
I did run configure (and clean_cache), but that was after the normal daily run, in which canvas turned up again. So it must be a change to the json files that are loaded every run that fixed it. But it is indeed very strange that data disappeared without any message at all.

**Comment by hikavdh** [comment]
Nah, the json files didn't change since nov 15th 3:53 GMT. If you didn't run --configure prior to canvas coming back, there must have been something in the data from one of the sources they corrected sometime last night. I'll see if I can find something in the code that could make it think that the data is invalid. The only reason I can think of is it cutting of all data before midnight the first day and after midnight the last day. So some date thing, but the change from summertime was a few weeks ago and vrt,be, which is the prime source for canvas should be unaffected by that as it uses GMT in the data.

**Comment by kyl416** [comment]
The changes I made didn't affect any of the channels you have listed as active in the log. It was just for the Vlaams version of National Geographic which had its humo source id change from 26 to 119, and the addition of Viceland Vlaanderen on humo, nieuwsblad and primo.

**Comment by hikavdh** [comment]
I know! I just found it very coincidental that the problem with canvas started at about the time of the change and humo does use the database to determine on which page a channel is. so I could not beforehand rule it out.
