### ISSUE TITLE
Use Production Year as Season Number if None Available

### ISSUE THREAD

**Issue by mitchellklijs** [tvgrabbers/tvgrabpyAPI#39]
Here's an idea:

When no season number is available for a programme (either from sources or TheTVDB), the season is assumed to be 1. (No season number is specified, so many PVR's interpret this as season 1; as per XMLTV specification; https://github.com/XMLTV/xmltv/blob/master/xmltv.dtd#L377).

```xml
    <episode-num system="xmltv_ns"> . 83 . </episode-num>
```

When recording this provides a problem where episodes from different years (mainly daily shows) are interpreted as the same episode. Automatic recording systems might therefore not record these new episodes and episodes from different years get put in the same directory (depending on the recording configuration of course).

For most of these daily shows the production year is know. A configurable option could be added that uses the production year as season number. For example for 2019, this would look like this:

```xml
    <episode-num system="xmltv_ns">2018 . 83 . </episode-num>
```

*(Because of the 0-indexed numbers)*

Maybe we could even use the genre to determine if this behavior should be enabled (for example News).

If anyone has additional ideas that I missed, please mention them!

**Comment by hikavdh** [comment]
Nice idea and actually used on several sources. The problem is to determine when to apply this.

**Comment by mitchellklijs** [comment]
Yeah, determining when to do this would be a bit tricky.

Some ideas:
- Just turn it on for all shows that don't have season information (I don't think this is desired)
- Make it an option per channel / channel group
- Detect daily/weekly/recurring shows by analysing the guide (this would entail saving information for past days)
- Doing a search on TheTVDB (as this also specifies if shows are recurring
- Use the genre to determine when to enable this behavior.
- Make it configureable / adjustable on a per program basis (in a config file)

Did I miss anything?

**Comment by hikavdh** [comment]
This is a process that comes in code after merging. I'll look at it when I'm reviewing this code. So not in the near future.

**Comment by kyl416** [comment]
The problem is for everyone of those, there's a bunch of exceptions to the rule that would do more harm than good.

TheTVDB is not 100% reliable, there's a bunch of shows that can't be matched. Like kids shows and cartoons composed of shorts, while TheTVDB's policy is to list each short as a seperate episode. Plus because of infighting among editors certain popular shows are locked down, so Dutch language episode titles are not available to match. As well as weird things where the Netherlands and Flanders use different names for their dubs/subs, and in some cases the name and episode title varies from channel to channel in the same country. There's also the duplicate name issue resulting in false matches. We can only do so much with the aliases, but when multiple channels are airing both the remake and the originals, one of them isn't going to match.

Doing it by genres is hard because NPO and RTL don't provide genres, tvgids.nl's current state doesn't provide subgenres to identify soaps who number their shows differently, tvgids.tv does weird things that result in shows they want to highlight not being able to match, vpro provides some minimal genre details, humo and nieuwsblad have their own issues where one of them always uses the original language for titles, horizon is better but they have a bunch of timing issues for several major channels like RTL and Comedy Central that prevent them from being used as a prime_source. Then we got each source treating things like cartoons and kids programming differently. Some classify them as soap/series with something like "jeugd" or "animatie" or "tekken" as the subgenre, others lump all kids content with "jeugd" as the main genre and use the subgenre to classify what type of content it is, but because of the reasons above, we don't always have access to a subgenre. Then there's some that only categorizes things based on the genre instead of having unique genres for series, specials, sports, news and movies.

Soaps also creates an issue with the year thing because the international ones are several months behind the original country, and in some cases with RTL they have classic episodes in rotation too so we can't just slap the current year.

Analyzing based on daily/weekly isn't going to be reliable. We have channels that repeat shows in blocks several times a day, others shows that only air once a week, others that only air weekdays, others that only air on weekends.

The program specific thing is hard to do since we have 350+ channels and counting, each with different sources available providing varying details and timings. Along with issues with people using customizations in their .set file if they prefer the original language title or the Dutch/Vlams translation.

**Comment by mitchellklijs** [comment]
I get that there isn't a simple solution to this. Maybe we can use this issue to brainstorm further about this idea.

If this ever get's implemented, it will probably be something that has to be "smart" in a way that it can use multiple techniques based on configurations per channel and data that it fetches from the sources.
