### ISSUE TITLE
Memory usage?

### ISSUE THREAD

**Issue by alex341** [tvgrabbers/tvgrabpyAPI#43]
I understand there are some issues with the TVgids.nl and therefor the duration of a complete EPG-data-grabbing run.

Since I had some other issues on my Synology NAS (DS415Play), I was monitoring the CPI and memory usage by the NAS. Seems that tv_grab_nl3.py is using a growing amount of memory, during its run. This is of course not a problem on a PC, but on a NAS, with limited CPU and memory resources it slows down all not only other processes, but itself as well. 

Of course I do not know exactly how tv_grab works, but it seems it builds up a data file with the EPG data. Once it is finished with all the data gathering, it writes the result to the designated directory / file. If this is the case, there are 2 issues to be considered:
1. If a (fatal) error occurs during the grabbing process, the gathered data and used time is lost.
2. The memory usage keeps growing.

Would it be possible to write the results after each step (after each source, retrieved day and/or channel to the database / XML file and releasing the memory after successful doing so?

**Comment by hikavdh** [comment]
See the wiki on resource usage https://github.com/tvgrabbers/tvgrabpyAPI/wiki/resources
All data from a page once processed is already stored in the database.

**Comment by alex341** [comment]
Hi Hika,
Tnx for the quick respons! 
Your link leads me to an older version (I am using your latest 1.0.9 version) and before TVGids.nl gave errors (see #41 and #42 ). 
Besides that, in your link I see a fair amount of memory usage (cache). The DS415Play has only 1024 MB memory and adding memory or placing a bigger memory unit is not possible. Is there an option the release memory during the process?

**Comment by hikavdh** [comment]
The cache memory in this example is from all kind of other processes running on this server and could with not to much performance loss get placed in swap, so make sure your swap partition is big enough and on the fastest disk available. 
In the example with 81 channels about 1.5 Gb is used by the grabber, similar to what version 2 used. The only way to reduce this is to create an algorithm that temporarily places part in a file, which would have a severe performance penalty, higher then letting your system manage swapping out part of it at need. 
Possibly some reduction in memory use could be found by a more aggressive release of old variables, but as the garbage collector in Python is quiet good, I doubt the impact will be big.
Alternately you can break your grab in two for half the channels each.

**Comment by hikavdh** [comment]
![sys-memory-24h](https://user-images.githubusercontent.com/11459311/60198428-d9730200-9841-11e9-9af5-8445a5d7ccf0.png)
Here the memory usage on my system for the past 24 hour

**Comment by kyl416** [comment]
The fetched data isn't lost if you have issues and the process closes prematurely, it's all stored in the program_cache3.db file as it fetches data. The next time you run the command it will use the existing data from the cache file and only refetches the current day and fetches any missing days that aren't in the cache.

The way it runs is that it fetches from multiple sources and then outputs a merged version of listings for each channel since various sources give us different levels of detail. (i.e. Episode titles, episode numbers, seasons, description, original country, omroep for the NPO channels, ratings, actors, years, genres, start/stop times, etc) So it's probably better to run the grabber on a computer with more RAM and then transfer the final xml file to your NAS server.

But if you have no choice but to use a low memory device, try grabbing less days and lower the value of max_simultaneous_fetches in your .conf file so it's not doing too many fetches at the same time.

Depending on the channels you selected you might want to disable some of the other sources by using the --disable-source and --disable-detail-source flags. Like if you don't grab any Vlaams channels you might want to disable sources 6 (humo.be), 8 (Nieuwsblaad), 9 (primo.eu) and 10 (vrt.be), since for the few Dutch channels those sources have like NPO and Discovery the other sources like Horizon, VPRO and tvgids.nl provide most of the data. tvgids.tv is also barely used in the final output for most channels so you might want to disable source 1.
 
Also, provided that everything is going well, you might want to try lowering the log_level and match_log_level values in your .conf file
