### ISSUE TITLE
JSON error

### ISSUE THREAD

**Issue by jcjdammers** [tvgrabbers/tvgrabpyAPI#55]
I got the following error today on Sun Mar 7 04:00:22 CET 2021.

The url: https://raw.githubusercontent.com/tvgrabbers/sourcematching/master/tv_grab_nl.json gave JSON error: Expecting property name enclosed in double quotes: line 1933 column 67 (char 68193)
File: "/var/lib/tvgrabpyAPI/tv_grab_nl.json" not found or could not be accessed.
Error reading the datafile on github.

**Comment by kyl416** [comment]
It was a temporary typo in one of the sourcematching files that was quicky fixed, your download happened to occur in that 5 minute span before it was fixed.

Also some advice, it's best not to schedule a download on the hour. Not only does that put a strain on some servers because a bunch of 3rd party software likes defaulting to on the hour. That's also when many of the sources push their schedule updates. Like when Humo, vrt, tvgids and Horizon do their updates for a few minutes some channels are missing blocks of data. A better time to schedule it is a random minute between :15-:30.

**Comment by jcjdammers** [comment]
Thanks for the fix and the tip !!

**Comment by jcjdammers** [comment]
Lately I get a lot of empty pages returned for horizon.tv, see example below and the attached log-file of my tonight's run.
I have never had this before.
Do you know if there is a problem?

[08_tv_grab_nl3_py.conf.log](https://github.com/tvgrabbers/tvgrabpyAPI/files/6099879/08_tv_grab_nl3_py.conf.log)

2021-03-08 04:28:06 CET: horizon.tv returned an empty page for channel: NL: SBS 6 HD (0-36).
2021-03-08 04:28:06 CET:     We assume the rest to be empty!

**Comment by kyl416** [comment]
Horizon changed the format of their station IDs last week, you need to rerun --configure and it will update the entries in your tv_grab_nl3_py.conf file.

VPRO also made some changes involving Discovery and some of their Radio stations, along with adding some additional channels like NPO 1 Extra, so I pushed an update that will prompt people to rerun configure next time they do a grab.
